tasks:
  - init: |
          rustup target add wasm32-unknown-unknown
          npm install -g near-cli near-api-js
          npm install nft.storage
          yarn build

    command: yarn start
ports:
  - port: 1234
    onOpen: open-browser
